In [ ]:
import sys
sys.executable

'/home/erinardo_adm/Projetos_e_Cursos/personal_projects/projetos_semanais/medical-no-shows/.venv3.12/bin/python'

In [4]:
import pandas as pd
pd.__version__

'3.0.5'

In [5]:
pd.set_option('display.max_rows', 999)
pd.set_option('display.max_columns', 0)
pd.reset_option('display.max_rows')
pd.set_option('display.min_rows', 15) # Só estou rodando para fins didáticos, porque essa visualização seria feita facilmente com o método .head(50)
display(pd.get_option('display.max_rows'))
display(pd.get_option('display.min_rows'))
pd.get_option('display.max_columns')

60

15

0

In [6]:
df = pd.read_csv('../data/bronze/KaggleV2-May-2016.csv')
df.shape

(110527, 14)

In [7]:
df.columns # Assim é o básico e vem tudo bagunçado.

Index(['PatientId', 'AppointmentID', 'Gender', 'ScheduledDay',
       'AppointmentDay', 'Age', 'Neighbourhood', 'Scholarship', 'Hipertension',
       'Diabetes', 'Alcoholism', 'Handcap', 'SMS_received', 'No-show'],
      dtype='str')

In [8]:
pd.DataFrame(df.columns) #Outra forma de já ter a tabela, sem nominar a coluna.

                 0
0        PatientId
1    AppointmentID
2           Gender
3     ScheduledDay
4   AppointmentDay
5              Age
6    Neighbourhood
7      Scholarship
8     Hipertension
9         Diabetes
10      Alcoholism
11         Handcap
12    SMS_received
13         No-show

In [9]:
pd.DataFrame(df.columns, columns=['Nome da Coluna']) # Já esse modo você consegue nominar.

    Nome da Coluna
0        PatientId
1    AppointmentID
2           Gender
3     ScheduledDay
4   AppointmentDay
5              Age
6    Neighbourhood
7      Scholarship
8     Hipertension
9         Diabetes
10      Alcoholism
11         Handcap
12    SMS_received
13         No-show

In [10]:
df.dtypes # Aqui traz todos os tipos de dados das colunas e como foram pensadas para acomodar o tamanho de cada tipo. Você pode utilizar essa informação para montar a sua tabela no SQL.

PatientId         float64
AppointmentID       int64
Gender                str
ScheduledDay          str
AppointmentDay        str
Age                 int64
Neighbourhood         str
Scholarship         int64
Hipertension        int64
Diabetes            int64
Alcoholism          int64
Handcap             int64
SMS_received        int64
No-show               str
dtype: object

In [11]:
df.head(50)

       PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
0   2.987250e+13        5642903      F  ...       0            0       No
1   5.589978e+14        5642503      M  ...       0            0       No
2   4.262962e+12        5642549      F  ...       0            0       No
3   8.679512e+11        5642828      F  ...       0            0       No
4   8.841186e+12        5642494      F  ...       0            0       No
5   9.598513e+13        5626772      F  ...       0            0       No
6   7.336882e+14        5630279      F  ...       0            0      Yes
7   3.449833e+12        5630575      F  ...       0            0      Yes
8   5.639473e+13        5638447      F  ...       0            0       No
9   7.812456e+13        5629123      F  ...       0            0       No
10  7.345362e+14        5630213      F  ...       0            0       No
11  7.542951e+12        5620163      M  ...       0            1      Yes
12  5.666548e+14        5634718      F  ...       0            0       No
13  9.113946e+14        5636249      M  ...       0            0       No
14  9.988472e+13        5633951      F  ...       0            0       No
15  9.994839e+10        5620206      F  ...       0            1       No
16  8.457439e+13        5633121      M  ...       0            0       No
17  1.479497e+13        5633460      F  ...       0            0      Yes
18  1.713538e+13        5621836      F  ...       0            1       No
19  7.223289e+12        5640433      F  ...       0            0       No
20  6.222575e+14        5626083      F  ...       0            0      Yes
21  1.215484e+13        5628338      F  ...       0            0      Yes
22  8.632298e+14        5616091      M  ...       0            1      Yes
23  2.137540e+14        5634142      F  ...       0            0       No
24  8.734858e+12        5641780      F  ...       0            0       No
25  5.819370e+12        5624020      M  ...       0            1       No
26  2.578785e+10        5641781      F  ...       0            0       No
27  1.215484e+13        5628345      F  ...       0            0       No
28  5.926172e+12        5642400      M  ...       0            0       No
29  1.225776e+12        5642186      F  ...       0            0       No
30  3.428156e+11        5628068      F  ...       0            0       No
31  3.112849e+11        5628907      M  ...       0            0      Yes
32  5.288356e+13        5637908      M  ...       0            0       No
33  7.653517e+12        5616921      F  ...       0            1       No
34  1.999976e+13        5637963      F  ...       0            0       No
35  7.816264e+13        5637968      M  ...       0            0       No
36  7.298459e+13        5637975      F  ...       0            0       No
37  1.578132e+12        5637986      F  ...       0            0       No
38  5.873316e+12        5609446      M  ...       0            1       No
39  1.455623e+13        5639644      F  ...       0            0       No
40  9.968684e+14        5635881      F  ...       0            0       No
41  8.224325e+14        5633339      F  ...       0            0       No
42  2.596543e+13        5632906      F  ...       0            0       No
43  7.155896e+13        5641620      F  ...       0            0       No
44  2.741649e+11        5635414      F  ...       0            0      Yes
45  4.982379e+12        5635842      F  ...       0            0       No
46  1.379437e+11        5615608      M  ...       0            1       No
47  5.894585e+11        5633116      F  ...       0            0       No
48  8.545415e+12        5618643      F  ...       0            1      Yes
49  9.223559e+13        5534656      F  ...       0            1      Yes

[50 rows x 14 columns]

#### Se vc usar 3 argumentos para o parâmetro 'by', vc tem que concatenar exatamente com a mesma quantidade em ascending.

In [31]:
df_sorted = df.sort_values(by=['Neighbourhood', 'Age', 'Gender'], ascending=[True, True, True], na_position='first')
df_sorted

           PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
84113   9.816959e+12        5768785      F  ...       0            0       No
24988   9.598723e+13        5595387      F  ...       0            0      Yes
53972   4.672745e+12        5668760      M  ...       0            0       No
29322   5.267573e+13        5647604      F  ...       0            0       No
39616   5.267573e+13        5681949      F  ...       0            0       No
109204  9.255818e+13        5774386      M  ...       0            0       No
85557   5.494460e+10        5699196      M  ...       0            1       No
...              ...            ...    ...  ...     ...          ...      ...
99402   8.554348e+14        5714278      F  ...       0            1       No
30487   1.571164e+13        5677388      M  ...       0            0       No
22028   4.131145e+13        5675297      F  ...       0            0       No
22050   4.131145e+13        5732659      F  ...       0            0       No
22099   7.918144e+12        5681883      F  ...       0            0       No
24131   1.397160e+12        5664301      F  ...       0            0       No
24150   1.397160e+12        5664330      F  ...       0            0       No

[110527 rows x 14 columns]

Atomização da Sintaxe do Gerenciador de ContextoA palavra-chave with: Inicia a construção de um escopo isolado no Python. Ela invoca os métodos internos __enter__ (que altera temporariamente as configurações do Pandas) e __exit__ (que limpa tudo e restaura o padrão assim que a indentação acaba).A função display(): No Jupyter, se você apenas escrever o nome do objeto na última linha do bloco with, ele pode não renderizar de forma correta por limitações visuais de encadeamento do bloco. Usar a função nativa display(df_sorted) força o Jupyter a renderizar a tabela HTML interativa de forma explícita enquanto o contexto ainda está ativo.

In [13]:
with pd.option_context('display.min_rows', 20, 'display.max_columns', 0):
    display(pd.get_option('display.min_rows'))
    display(pd.get_option('display.max_columns'))
    display(df_sorted)

20

0

           PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
84112   9.816959e+12        5768785      F  ...       0            0       No
24987   9.598723e+13        5595387      F  ...       0            0      Yes
53971   4.672745e+12        5668760      M  ...       0            0       No
29321   5.267573e+13        5647604      F  ...       0            0       No
39615   5.267573e+13        5681949      F  ...       0            0       No
109203  9.255818e+13        5774386      M  ...       0            0       No
85556   5.494460e+10        5699196      M  ...       0            1       No
67179   7.235687e+12        5427853      F  ...       0            0       No
1145    5.853129e+11        5623706      F  ...       0            0       No
43467   1.822535e+13        5729645      F  ...       0            0       No
...              ...            ...    ...  ...     ...          ...      ...
22004   2.231177e+13        5732649      F  ...       0            0       No
22011   8.554348e+14        5709290      F  ...       0            0       No
24133   5.157596e+13        5686728      F  ...       0            0       No
99401   8.554348e+14        5714278      F  ...       0            1       No
30486   1.571164e+13        5677388      M  ...       0            0       No
22027   4.131145e+13        5675297      F  ...       0            0       No
22049   4.131145e+13        5732659      F  ...       0            0       No
22098   7.918144e+12        5681883      F  ...       0            0       No
24130   1.397160e+12        5664301      F  ...       0            0       No
24149   1.397160e+12        5664330      F  ...       0            0       No

[110527 rows x 14 columns]

In [14]:
display(pd.get_option('display.min_rows'))
df_sorted = df_sorted.sort_values(by='Age', ascending=True).reset_index(drop=True)
# display(df.sort_values(by='AppointmentID', ascending=True).reset_index())
df.index = df.index +1
display(df_sorted)

15

           PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
0       4.659432e+14        5775010      F  ...       0            0       No
1       9.865274e+13        5651893      F  ...       0            0       No
2       4.298978e+11        5719406      F  ...       0            1       No
3       1.822535e+13        5729645      F  ...       0            0       No
4       5.853129e+11        5623706      F  ...       0            0       No
5       7.844758e+13        5699962      M  ...       0            0       No
6       3.728549e+13        5684826      M  ...       0            0       No
...              ...            ...    ...  ...     ...          ...      ...
110520  2.342836e+11        5751563      F  ...       0            0       No
110521  9.762948e+14        5651757      F  ...       0            0       No
110522  3.196321e+13        5562812      F  ...       1            0      Yes
110523  3.196321e+13        5744037      F  ...       1            0       No
110524  3.196321e+13        5700278      F  ...       1            0      Yes
110525  3.196321e+13        5700279      F  ...       1            0      Yes
110526  7.482346e+14        5717451      F  ...       0            1       No

[110527 rows x 14 columns]

In [ ]:
with pd.option_context('display.max_rows', 100): # Depois do gerenciador de contexto, o qual é uma função, 'pd.option_context' é preciso que o código logo abaixo esteja com 1 identação, senão, não funcionará. Esse código só funcionará nessa célula.
    display(df_sorted.sort_values(by='Age', ascending=False).head())
    
type(pd.option_context)

In [ ]:
df_sorted.info()